

export const TODOS_FETCH = 'TODOS_FETCH';
export const TODOS_FETCH_START = 'TODOS_FETCH_START';
export const TODOS_FETCH_SUCCEEDED = 'TODOS_FETCH_SUCCEEDED';
export const TODOS_FETCH_FAILED = 'TODOS_FETCH_FAILED';




export const OIDC_LOAD_USER = 'OIDC_LOAD_USER';
export const OIDC_LOAD_USER_SUCCEEDED = 'OIDC_LOAD_USER_SUCCEEDED';

export const INDEX_TIME_FETCH = 'INDEX_TIME_FETCH';
export const INDEX_TIME_FETCH_SUCCESSED = 'INDEX_TIME_FETCH_SUCCESSED';

export const INDEX_SENTENCE_FETCH = 'INDEX_SENTENCE_FETCH';
export const INDEX_SENTENCE_FETCH_SUCCEED = 'INDEX_SENTENCE_FETCH_SUCCEED';

export const INDEX_SENTENCE_HEART_FETCH = 'INDEX_SENTENCE_HEART_FETCH';
export const INDEX_SENTENCE_HEART_FETCH_SUCCEED = 'INDEX_SENTENCE_HEART_FETCH_SUCCEED';

export const INDEX_SETTINGS_MODAL_TOGGLE = 'INDEX_SETTINGS_MODAL_TOGGLE';
export const INDEX_SETTINGS_MODAL_TOGGLE_SUCCEED = 'INDEX_SETTINGS_MODAL_TOGGLE_SUCCEED';

export const INDEX_FOCUSES_FETCH = 'INDEX_FETCH_FOCUSES';
export const INDEX_FETCH_FOCUSES_START = 'INDEX_FETCH_FOCUSES_START';
export const INDEX_FETCH_FOCUSES_SUCCEED = 'INDEX_FETCH_FOCUSES_SUCCEED';

export const INDEX_FOCUS_ADD = 'INDEX_FOCUS_ADD';
export const INDEX_FOCUS_ADD_SUCCEED = 'INDEX_FOCUS_ADD_SUCCEED';

export const INDEX_FOCUS_MODAL_TOGGLE = 'INDEX_FOCUS_MODAL_TOGGLE';
export const INDEX_FOCUS_MODAL_TOGGLE_SUCCEED = 'INDEX_FOCUS_MODAL_TOGGLE_SUCCEED';


export const INDEX_FOCUS_REMOVE = 'INDEX_FOCUS_REMOVE';
export const INDEX_FOCUS_REMOVE_SUCCEED = 'INDEX_FOCUS_REMOVE_SUCCEED';

export const INDEX_FOCUS_COMPLETE ='INDEX_FOCUS_COMPLETE';
export const INDEX_FOCUS_COMPLETE_SUCCEED ='INDEX_FOCUS_COMPLETE_SUCCEED';

export const INDEX_FOCUS_PIN ='INDEX_FOCUS_PIN';
export const INDEX_FOCUS_PIN_SUCCEED ='INDEX_FOCUS_PIN_SUCCEED';

export const INDEX_WEATHER_FETCH = 'INDEX_WEATHER_FETCH';
export const INDEX_WEATHER_FETCH_SUCCEED = 'INDEX_WEATHER_FETCH_SUCCEED';

